[[constraint]]
  branch = "master"
  name = "github.com/datasift/go-charset"
  source = "github.com/stripe/go-charset"

[[constraint]]
  name = "github.com/elazarl/goproxy"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
