[[constraint]]
  branch = "master"
  name = "github.com/datasift/go-charset"
  source = "github.com/stripe/go-charset"

[[constraint]]
  name = "github.com/elazarl/goproxy"
  revision = "0890fc15d1b6428a674b8252a2d238ca589daf73"

[prune]
  go-tests = true
  unused-packages = true
